# Generated by Django 3.0.4 on 2020-04-06 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ck_index', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='yuangong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='员工名称')),
                ('age', models.CharField(max_length=2, verbose_name='年龄')),
                ('gender', models.BooleanField(verbose_name='性别')),
                ('groups', models.ManyToManyField(to='ck_index.groups', verbose_name='所属小组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='账号信息')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 'ck_yuangongInfo',
            },
        ),
    ]
