# Generated by Django 3.0.4 on 2020-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ck_index', '0001_initial'),
        ('ck_yuangong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gongsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('types', models.ManyToManyField(to='ck_index.types', verbose_name='公司类型')),
                ('yuangong', models.ManyToManyField(to='ck_yuangong.yuangong', verbose_name='员工信息')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
                'db_table': 'ck_gongsiInfo',
            },
        ),
    ]
