# Generated by Django 3.0.4 on 2020-04-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ck_yuangong', '0001_initial'),
        ('ck_gongsi', '0001_initial'),
        ('ck_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gongsi',
            name='types',
            field=models.ManyToManyField(to='ck_index.types', verbose_name='公司类型'),
        ),
        migrations.AddField(
            model_name='gongsi',
            name='yuangong',
            field=models.ManyToManyField(to='ck_yuangong.yuangong', verbose_name='员工信息'),
        ),
    ]
