# Generated by Django 3.0.4 on 2020-04-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allHistoryCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='总点击次数')),
                ('type', models.CharField(max_length=255, verbose_name='类型')),
            ],
            options={
                'verbose_name': '全站类型点击次数统计',
                'verbose_name_plural': '全站类型点击次数统计',
                'db_table': 'ty_allHistoryCount',
            },
        ),
    ]
