# Generated by Django 3.0.4 on 2020-04-07 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='种类名称')),
            ],
            options={
                'verbose_name': '种类',
                'verbose_name_plural': '种类',
                'db_table': 'bx_types',
            },
        ),
        migrations.CreateModel(
            name='baoxianInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='保险名称')),
                ('context', mdeditor.fields.MDTextField(verbose_name='保险详情')),
                ('img', models.CharField(max_length=255, verbose_name='图片链接')),
                ('fzr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='保险负责人')),
                ('types', models.ManyToManyField(to='bx_index.types', verbose_name='保险种类')),
            ],
            options={
                'verbose_name': '种类',
                'verbose_name_plural': '种类',
                'db_table': 'bx_Info',
            },
        ),
    ]
