# Generated by Django 3.0.4 on 2020-04-30 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='baoxianInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='保险名称')),
                ('context', mdeditor.fields.MDTextField(verbose_name='保险详情')),
                ('img', models.CharField(max_length=255, verbose_name='图片链接')),
            ],
            options={
                'verbose_name': '保险信息管理',
                'verbose_name_plural': '保险信息管理',
                'db_table': 'bx_Info',
            },
        ),
        migrations.CreateModel(
            name='dingdan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='用户信息')),
                ('dingdanhao', models.CharField(max_length=255, verbose_name='订单号')),
                ('baoxian_id', models.IntegerField(verbose_name='订单内的保险id')),
                ('price', models.IntegerField(verbose_name='订单价格')),
                ('is_paid', models.CharField(max_length=255, verbose_name='是否已经支付')),
            ],
            options={
                'verbose_name': '订单价格',
                'verbose_name_plural': '订单价格',
                'db_table': 'bx_dingdan_price',
            },
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='小组名称')),
            ],
            options={
                'verbose_name': '小组管理',
                'verbose_name_plural': '小组管理',
                'db_table': 'bx_groups',
            },
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='种类名称')),
            ],
            options={
                'verbose_name': '种类管理',
                'verbose_name_plural': '种类管理',
                'db_table': 'bx_types',
            },
        ),
        migrations.CreateModel(
            name='yuangong_bx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('groups', models.ManyToManyField(to='bx_index.groups', verbose_name='所属小组')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='账号信息')),
            ],
            options={
                'verbose_name': '员工管理',
                'verbose_name_plural': '员工管理',
                'db_table': 'bx_yuangong',
            },
        ),
        migrations.CreateModel(
            name='priceManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='保险价格')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='bx_index.baoxianInfo', verbose_name='保险名称')),
            ],
            options={
                'verbose_name': '保险价格',
                'verbose_name_plural': '保险价格',
                'db_table': 'bx_price',
            },
        ),
        migrations.AddField(
            model_name='baoxianinfo',
            name='fzr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bx_index.yuangong_bx', verbose_name='保险负责人'),
        ),
        migrations.AddField(
            model_name='baoxianinfo',
            name='types',
            field=models.ManyToManyField(to='bx_index.types', verbose_name='保险种类'),
        ),
    ]
