# Generated by Django 3.0.4 on 2020-04-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bx_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baoxianinfo',
            options={'verbose_name': '保险信息管理', 'verbose_name_plural': '保险信息管理'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': '种类管理', 'verbose_name_plural': '种类管理'},
        ),
    ]
