# Generated by Django 3.0.4 on 2020-04-20 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bx_index', '0002_auto_20200409_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='小组名称')),
            ],
            options={
                'verbose_name': '小组管理',
                'verbose_name_plural': '小组管理',
                'db_table': 'bx_groups',
            },
        ),
        migrations.CreateModel(
            name='yuangong_bx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('groups', models.ManyToManyField(to='bx_index.groups', verbose_name='所属小组')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='账号信息')),
            ],
            options={
                'verbose_name': '员工管理',
                'verbose_name_plural': '员工管理',
                'db_table': 'bx_yuangong',
            },
        ),
        migrations.AlterField(
            model_name='baoxianinfo',
            name='fzr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bx_index.yuangong_bx', verbose_name='保险负责人'),
        ),
    ]
