# Generated by Django 3.0.4 on 2020-04-09 13:17

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100, verbose_name='歌曲名称')),
                ('image', models.CharField(max_length=255, verbose_name='图片链接')),
                ('song_auth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sing.SingInfo', verbose_name='唱曲人')),
                ('song_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sing.Zhuangji', verbose_name='所属专辑')),
                ('song_type', models.ManyToManyField(to='sing.Flag', verbose_name='歌曲标签')),
            ],
            options={
                'verbose_name': '歌曲信息',
                'verbose_name_plural': '歌曲信息',
                'db_table': 'ty_Song_Info',
            },
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('list_name', models.CharField(max_length=100, verbose_name='歌单信息')),
                ('image_URL', models.CharField(max_length=255, verbose_name='图片链接')),
                ('list_info', mdeditor.fields.MDTextField(verbose_name='歌单信息')),
                ('list_songs', models.ManyToManyField(to='song.SongInfo', verbose_name='歌单列表')),
                ('list_type', models.ManyToManyField(to='sing.Flag', verbose_name='歌单标签')),
            ],
            options={
                'verbose_name': '歌单信息',
                'verbose_name_plural': '歌单信息',
                'db_table': 'ty_List_Info',
            },
        ),
        migrations.CreateModel(
            name='iFrameM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='内嵌框架')),
                ('sing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='song.SongInfo', verbose_name='歌曲名')),
            ],
            options={
                'verbose_name': '内嵌框架管理',
                'verbose_name_plural': '内嵌框架管理',
                'db_table': 'ty_iframe',
            },
        ),
    ]
