# Generated by Django 3.0.4 on 2020-04-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iframem',
            old_name='sing',
            new_name='song',
        ),
    ]
