# Generated by Django 3.0.4 on 2020-04-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ck_yuangong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cangku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='仓库名称')),
                ('number', models.CharField(max_length=5, verbose_name='仓库编号')),
                ('shuliang', models.CharField(max_length=5, verbose_name='仓库数量')),
                ('forWho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ck_yuangong.yuangong', verbose_name='管理方')),
            ],
            options={
                'verbose_name': '仓库信息',
                'verbose_name_plural': '仓库信息',
                'db_table': 'ck_cangku',
            },
        ),
        migrations.CreateModel(
            name='huojia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='货架名称')),
                ('number', models.CharField(max_length=5, verbose_name='货架编号')),
                ('shuliang', models.CharField(max_length=5, verbose_name='货架数量')),
                ('forWhichCangku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ck_cangku.cangku', verbose_name='仓库所属')),
                ('forWho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ck_yuangong.yuangong', verbose_name='管理方')),
            ],
            options={
                'verbose_name': '货架信息',
                'verbose_name_plural': '货架信息',
                'db_table': 'ck_huojia',
            },
        ),
        migrations.CreateModel(
            name='wupin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='物品信息')),
                ('number', models.CharField(max_length=5, verbose_name='物品编号')),
                ('shuliang', models.CharField(max_length=5, verbose_name='物品数量')),
                ('forWhichHuojia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ck_cangku.huojia', verbose_name='货架所属')),
            ],
            options={
                'verbose_name': '物品信息',
                'verbose_name_plural': '物品信息',
                'db_table': 'ck_wupin',
            },
        ),
    ]
